name: protobuf-parser
version: 0.1.0.0
github: "antonkesy/protobuf-parser"
license: BSD-3-Clause
author: "Anton Kesy"
maintainer: "antonkesy@gmail.com"
copyright: "2023 Anton Kesy"

extra-source-files:
  - README.md
  - CHANGELOG.md

description: Please see the README on GitHub at <https://github.com/antonkesy/protobuf-parser#readme>

dependencies:
  - base >= 4.7 && < 5
  - parsec >= 3.1.16 && < 4
  - prettyprinter >= 1.7.1 && < 2
  - optparse-applicative >= 0.17.0

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints
  - -Werror -W -fwarn-unused-imports -fwarn-unused-binds -fwarn-orphans
  - -fwarn-unused-matches -fwarn-unused-do-bind -fwarn-wrong-do-bind
  - -fwarn-missing-signatures -fno-warn-partial-type-signatures
  - -Wredundant-constraints -rtsopts

library:
  source-dirs: src

executables:
  protobuf-parser-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - protobuf-parser

tests:
  protobuf-parser-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - protobuf-parser
      - HUnit
